name: Self-VPS Deployment

on:
  push:
    branches: ["develop"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: |
          echo ${{ secrets.ENV_FILE }} > .env
          ls -a
          npm ci
          npm run build --if-present

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: ./react/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USER}}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          remote_port: 22000
